### PR TITLE
Integrate Nano cryptocurrency in V4V spec, adding documentation

### PR DESCRIPTION
**Pull request by koczadly**
This adds a Value 4 Value specification and associated constants for the [Nano](https://nano.org) cryptocurrency.

If there's another procedure for registering and declaring a cryptocurrency in the V4V spec, please let me know and I'll be sure to do it.

### CODE REVIEW

**Comment by brianoflondon** [comment]
There is one constraint and perhaps we do need to lift it: the current Value Block spec says only one type of value block per feed. I always thought it should be more but I backed down on that.

I'm happy to re-add my Hive suggestion too but I'm not in a position to drive adoption of it.

**Comment by dellagustin** [comment]
> There is one constraint and perhaps we do need to lift it: the current Value Block spec says only one type of value block per feed. I always thought it should be more but I backed down on that.

Related to that - https://github.com/Podcastindex-org/podcast-namespace/issues/300

**Comment by daveajones** [comment]
@zhyatt Could you resolve the conflicts or do a new PR on this one?  I got behind in merging some other ones and it looks like it messed you up.

**Comment by koczadly** [comment]
@daveajones I have resolved the conflicts.

The appendix section appears to be very lightning specific, and is a nested heading of the lightning section. In my commit I have kept the appendix together under the lightning heading, but this may be out of place?

I do think the document could perhaps do with some restructuring. For instance, the value override example is shown under the Supported currencies > Lightning heading, whereas it's more of a general example.

It may also be worth hiding the supported currencies section within `<details>` blocks (if they're still supported?), allowing the reader to expand only the relevant sections.

**Comment by daveajones** [comment]
Thanks!!

**Pull request merged**
