### PR TITLE
Added an explanation and use case for customKey/customValue

### PR DESCRIPTION
**Pull request by brianoflondon**
I didn't really understand this till it suddenly clicked and I started using it.

### CODE REVIEW

**Comment by brianoflondon** [comment]
I also withdraw an earlier proposal that makes no sense now I figured out I should be using `customKey` `customValue` instead.

**Comment by brianoflondon** [comment]
We can certainly refine these together.

**Comment by daveajones** [comment]
Reviewing this.

**Comment by daveajones** [comment]
Sorry, I’ve just been foggy headed from being sick and didn’t want to miss something in review since it has a bunch of commits to look at.  So I thought I’d wait until I got back to thinking straight.   I’ll do my best to look and merge today or tomorrow. Before the weekend.

**Comment by brianoflondon** [comment]
@daveajones this has been sitting so long it's now getting conflicts. The main thing I added was a very useful section on customKey customValue. I also added a nice regex.

My own repo is now a mess and I'm not sure how to recover and fix at this point.

**Comment by brianoflondon** [comment]
I think I fixed the conflict.

**Comment by daveajones** [comment]
Sorry, I've just been way behind on this type of work and needed to have a fresh brain to review this since it was a large PR.

**Pull request merged**
