### PR TITLE
Include the bLIP 10 Specification in this Repository

### PR DESCRIPTION
**Pull request by Alwin-Stockinger**
This PR addresses [https://github.com/Podcastindex-org/podcast-namespace/discussions/506](https://github.com/Podcastindex-org/podcast-namespace/discussions/506).

It also includes the action proposed in [https://github.com/Podcastindex-org/podcast-namespace/discussions/500](https://github.com/Podcastindex-org/podcast-namespace/discussions/500).

## Changes to the [original document](https://github.com/lightning/blips/blob/master/blip-0010.md):

- Removed the blip number, title and status from the heading and changed Author to Original Author
- Modified the abstract to better fit with the rest of Podcasting 2.0
- Turned codeblocks into json codeblocks
- Corrected the Example in the Abstract to a valid json with double quotes instead of single quotes
- Made the “Formatting and encoding” section a little clearer
- Made clear that multiple fields for identifying podcast and episode can be added
- Added guid to “use any of `podcast`, `feedID` or `url`”
- Made `episode_guid` preferred field for identifying episode because `episode_guid` does not rely on the episode being in the index
- Put `ts`above `time` to reflect that ts is preferred
- Add `auto` option to action, as was proposed by @dhk2 in [https://github.com/Podcastindex-org/podcast-namespace/discussions/500](https://github.com/Podcastindex-org/podcast-namespace/discussions/500)
- Added to `boost_link` field description that it can be used for any action and that links may not contain podcast, episode AND timestamp, as Fountain currently only links to the episode not a timestamp.
- Switched recommended from `name` to `sender_name` because the receiver should know the name of their split anyway, but not the one of the sender
- Reformulated `sender_id` description
- Removed `pubkey`, `seconds_back`, `sender_key`, `sig_fields`, `signature` fields because no app is using them (Podverse sends the `pubkey` field but only puts the value “podverse-pubkey" in it)
- Removed `value_msat` because that information is in the invoice anyways
- Made `value_msat_total` **recommended** for numerology purposes
- Removed Motivation section
- Removed Rationale section
- Removed Universality section
- Removed Backwards Compatibility section
- Added Rust-V4V to Reference Implementations
- Added Examples & App Specifics section

### CODE REVIEW

**Comment by satoshisstream** [comment]
Good idea to remove the old/unused things.

**Comment by satoshisstream** [comment]
https://github.com/lightning/blips/pull/23

**Comment by Alwin-Stockinger** [comment]
> lightning/blips#23

Is there any automatic way we could keep both of them in sync somehow?

**Comment by satoshisstream** [comment]
Just link it I'd say; anyone can PR the lightning repo :)

**Comment by daveajones** [comment]
Thanks for this. Much easier to track now.

**Pull request merged**
